- src/main/kotlin/no/nav/amt/aktivitetskort/kafka/consumer/dto/ArrangorDto.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/utils/StringUtils.kt
- src/main/resources/application.properties
- src/test/kotlin/no/nav/amt/aktivitetskort/database/TestData.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/utils/StringUtilsKtTest.kt
https://trello.com/c/P59EiKB7/1134-akaas-og-aktivitetsplan-endre-casing-for-navn-p%C3%A5-tiltaksarrang%C3%B8r
Jeg har lagt inn et par ord som det ser finest ut om får bestemt casing, tar gjerne i mot forslag til flere :) (dette blir best effort, så det er ikke meningen å fange alt her)
> bruker titlecase for arrangørnavn

- src/main/kotlin/no/nav/amt/aktivitetskort/repositories/DeltakerRepository.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/StatusMapping.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/repositories/DeltakerRepositoryTest.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/service/HendelseServiceTest.kt
https://trello.com/c/k8QnHIrR/1136-flytt-feilregistrerte-aktivitetskort-til-avbrutt-kolonnen
> feilregistrerte deltakere skal få avbrutt evt. aktivitetskort

- src/main/kotlin/no/nav/amt/aktivitetskort/repositories/DeltakerRepository.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortService.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/HendelseService.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/IntegrationTest.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/kafka/consumer/KafkaListenerTest.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/mock/MockAktivitetArenaAclServer.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/mock/MockAmtArenaAclServer.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/mock/MockHttpServer.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/mock/MockMachineToMachineServer.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/utils/AsyncUtils.kt
Hvis det kommer tombstones for deltakere har kan vi ikke slette aktivitetskort som finnes for deltakeren. Vi avbryter istedet aktivitetskort som ikke står som fullført eller avbrutt fra før.
> Avbryt aktivitetskort for slettede deltakere

- src/main/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortService.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/HendelseService.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/StatusMapping.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/database/TestData.kt
https://trello.com/c/XejERE7G/1194-opprette-aktivitetskort-for-deltakelse-med-status-p%C3%A5begynt-registrering
> lager aktivitetskort for påbegynt registrering

- build.gradle.kts
- src/main/kotlin/no/nav/amt/aktivitetskort/domain/Deltaker.kt
https://trello.com/c/yb3KX77q/1192-endre-visningstekst-for-ikkemott-til-m%C3%B8tte-ikke-opp-i-deltakeroversikten-og-aktivitetskort
> endrer ordlyd for ikke møtt

- src/main/kotlin/no/nav/amt/aktivitetskort/domain/Deltaker.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/HendelseService.kt
https://trello.com/c/XejERE7G/1194-opprette-aktivitetskort-for-deltakelse-med-status-p%C3%A5begynt-registrering
> Pabegynt registrering statustekst

- gradle/wrapper/gradle-wrapper.properties
- src/main/kotlin/no/nav/amt/aktivitetskort/kafka/consumer/KafkaListener.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/repositories/DeltakerRepository.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/HendelseService.kt
- src/main/resources/db/migration/V12__deltaker-kafkaoffset.sql
- src/main/resources/db/migration/V13__deltaker-kafkaoffset-index.sql
- src/test/kotlin/no/nav/amt/aktivitetskort/database/TestDatabaseService.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/kafka/consumer/KafkaListenerTest.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/repositories/DeltakerRepositoryTest.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/service/HendelseServiceTest.kt
https://trello.com/c/NYC1nEu3/1199-sjekke-om-vi-sender-oppdaterte-aktivitetskort-n%C3%A5r-det-ikke-er-noen-endringer
> Lagre offset deltakere

- src/main/kotlin/no/nav/amt/aktivitetskort/service/HendelseService.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/service/HendelseServiceTest.kt
https://trello.com/c/jyqlgeVD/1252-fjerne-unleash-toggle-fra-amt-aktivitetskort-publisher-for-%C3%A5-skru-p%C3%A5-publisering
> fjerner unleashtoggle for å skru på sending av kort

- src/main/kotlin/no/nav/amt/aktivitetskort/domain/Deltaker.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/repositories/DeltakerRepository.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/HendelseService.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/repositories/DeltakerRepositoryTest.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/service/HendelseServiceTest.kt
https://trello.com/c/6VoYt84A/1311-feilfiks-ikke-oppdatere-aktivitetskort-hvis-det-ikke-er-reelle-endringer
> Gamledeltakere

- src/main/kotlin/no/nav/amt/aktivitetskort/internal/InternalController.kt
Hvis deltakeren har blitt slettet må vi kunne resende siste sendte melding.
> resender siste sendte akaas-melding for en deltaker

- src/main/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortService.kt
OpprettMelding-metoden som jeg har endret brukes kun når endringen kommer som følge av endring i deltakerliste eller endring i arrangør, eller hvis man sender på nytt manuelt. For sistnevnte blir dette helt likt som det var, men når vi mottar en endring på deltakerliste eller arrangør så hopper vi bare over de meldingene der deltakeren har blitt slettet hos oss.
> hopper over deltakere som er slettet

- src/main/kotlin/no/nav/amt/aktivitetskort/service/StatusMapping.kt
https://trello.com/c/QwFqcwEJ/1521-endring-p%C3%A5-etiketter-inn-til-aktivitetsplan
> etikett for utkast til påmelding

- src/main/kotlin/no/nav/amt/aktivitetskort/domain/Aktivitetskort.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/StatusMapping.kt
https://trello.com/c/u3cb3MLw/1408-status-feilregistrert
> legger til etikett for feilregistrert

- src/main/kotlin/no/nav/amt/aktivitetskort/domain/Deltaker.kt
https://trello.com/c/UIVUO58C/1388-legge-til-utdanning-som-en-%C3%A5rsak
> legger til utdanning som sluttårsak

- src/main/kotlin/no/nav/amt/aktivitetskort/domain/ManglerArenaIdException.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortService.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/HendelseService.kt
Skal revertes når vi har kommet gjennom hist-deltakerne
> midlertidig fiks for å ignorere hist-deltakere som mangler arenaid

- src/main/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortService.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortServiceTest.kt
Med denne endringen styrer vi om deltakerne skal behandles som om komet er master eller ikke kun basert på unleash-toggle og tiltakstype, ikke kilde eller cluster.
> forbedrer toggle-funksjonalitet for hvilke deltakere komet er master for

- src/main/kotlin/no/nav/amt/aktivitetskort/domain/Aktivitetskort.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/domain/AktivitetskortTest.kt
https://trello.com/c/W38mge5S/1543-endring-p%C3%A5-tiltakstype-og-navn-varig-tilrettelagt
> Sett tittel pa aktivitetskort for VTA / VASV

- src/main/kotlin/no/nav/amt/aktivitetskort/repositories/DeltakerRepository.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortService.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/unleash/UnleashToggle.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortServiceTest.kt
https://trello.com/c/2jW2Jep2/1803-etter-lansering-endre-i-appene-som-sjekker-om-komet-er-master-for-deltakere-slik-at-komet-alltid-er-master-for-aft
Flyttet også alle unleash-togglegreiene inn i en egen UnleashToggle (samme som i amt-deltaker) så det er lettere å holde oversikt over toggles som brukes.
> endrer toggle så vi alltid er master for AFT

- src/main/kotlin/no/nav/amt/aktivitetskort/domain/Aktivitetskort.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/domain/Tiltak.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/kafka/consumer/dto/DeltakerlisteDto.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/database/TestData.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/domain/AktivitetskortTest.kt
https://trello.com/c/89vKWKO6/1958-oppdatere-hardkodede-navn-p%C3%A5-digiopparb
> fjerner egen regel for digiopparb og annen kode som ikke har effekt mer

- src/main/kotlin/no/nav/amt/aktivitetskort/unleash/UnleashToggle.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/database/TestData.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortServiceTest.kt
https://trello.com/c/VtRl4j9E/1928-etter-lansering-legge-til-de-tre-nye-tiltakstypene-i-listen-over-tiltak-vi-alltid-er-master-for
Endret også på testene så defaultoppførsel er sånn det skal være for de nye tiltakstypene (testene feiler ellers når vi legger til lenker for nye tiltakstyper)
> komet er alltid master for oppfølging, arr og avklaring

- src/main/kotlin/no/nav/amt/aktivitetskort/unleash/UnleashToggle.kt
https://trello.com/c/v4xePS94/1929-etter-lansering-legge-til-de-to-neste-tiltakstypene-i-listen-over-tiltak-vi-kanskje-er-master-for
> legger til nye tiltakstyper

- src/main/kotlin/no/nav/amt/aktivitetskort/internal/InternalController.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/repositories/MeldingRepository.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortService.kt
https://trello.com/c/IqBk6DtN/2023-vi-har-280-aktivitetskort-som-har-samme-id-som-et-annet-aktivitetskort-p%C3%A5-annen-deltaker
PS, den koden her er kun relevant fram til pr https://github.com/navikt/amt-aktivitetskort-publisher/pull/226 er merget men måtte finne en løsning siden den andre ikke kan merges mens denne feilen er i prod
> Intern endepunkt for å rette opp i feil hvor flere deltakere har fått samme meldingsid

- src/main/kotlin/no/nav/amt/aktivitetskort/internal/InternalController.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/repositories/MeldingRepository.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortService.kt
https://trello.com/c/IqBk6DtN/2023-vi-har-280-aktivitetskort-som-har-samme-id-som-et-annet-aktivitetskort-p%C3%A5-annen-deltaker
> Må også upserte id(denne endringen skal revertes)

- src/main/kotlin/no/nav/amt/aktivitetskort/internal/InternalController.kt
https://trello.com/c/94dCO0nA/2095-akas-returnererte-ny-aktivitetskortid-for-person-som-allerede-har-aktivitetskort
> Api for å relaste mange deltakere

- src/main/kotlin/no/nav/amt/aktivitetskort/internal/InternalAPI.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/kafka/consumer/KafkaConsumer.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/KafkaConsumerService.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/kafka/consumer/KafkaConsumerTest.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/service/KafkaConsumerServiceTest.kt
https://trello.com/c/7yIBq6Ke/2183-rename-consumere-producere-og-api
> Renamer klasser for å passe med nye kodekonvensjoner

- src/main/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortService.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/service/KafkaConsumerService.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortServiceTest.kt
https://trello.com/c/JlUeBgqa/2233-oppdatering-feiler-n%C3%A5r-vi-f%C3%A5r-endring-p%C3%A5-arrang%C3%B8r-og-aktivitetskort-ikke-er-i-aktiv-oppf%C3%B8lgingsperiode
Andre typer feil kan fortsatt tryne
> Retter feil som gjør at jobben krasjer når man får oppdatering på arrangør og ett eller flere aktivitetskort ikke er i en aktiv oppfølgingsperiode

- src/main/kotlin/no/nav/amt/aktivitetskort/service/StatusMapping.kt
https://trello.com/c/4eFoFgUW/2228-aktivitetskort-for-kurstiltak-s%C3%B8kt-inn-og-utkast
Det er ønsket at søkt inn skal være i planlegges kolonne
> søkt inn skal ligge i planlegges

- src/main/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortService.kt
https://trello.com/c/4eFoFgUW/2228-aktivitetskort-for-kurstiltak-s%C3%B8kt-inn-og-utkast
> Vise lenke også på tiltakstyper som vi ikke er master for

- build.gradle.kts
- src/main/kotlin/no/nav/amt/aktivitetskort/domain/Aktivitetskort.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/domain/Tiltak.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/internal/InternalAPI.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/kafka/consumer/dto/DeltakerlisteDto.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/kafka/producer/dto/AktivitetskortPayload.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/repositories/DeltakerlisteRepository.kt
- src/main/kotlin/no/nav/amt/aktivitetskort/unleash/UnleashToggle.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/database/TestData.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/domain/AktivitetskortTest.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/service/AktivitetskortServiceTest.kt
- src/test/kotlin/no/nav/amt/aktivitetskort/service/KafkaConsumerServiceTest.kt
https://trello.com/c/2OPyT6SH/2467-tilrettelegge-applikasjoner-for-%C3%A5-lese-inn-nye-deltakertyper
> Bumper lib og legger inn nye tiltakskoder
